language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
deploy:
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "Uys640Ut3iHTIfKzrnRlLeTCPV+ov9JPAsrEeaEc4V9KLgoejKxzd3rQCx4yBZVdB0hQhaC4C1kEck51LA0xtWtea60czLE40xuEYmKmYmERTec5m0wL0pEwVsqnfpBRX689JhFnZhJ840UTtH9acJjvkBbHJUrwEnx1tfHWfuw="
    on:
      tags: true
      all_branches: true
